services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'

  App\EventListener\JWTInvalidListener:
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onJWTInvalid }

  App\EventListener\JWTExpiredListener:
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: onJWTExpired }

  App\EventListener\JWTNotFoundListener:
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onJWTNotFound }

  App\EventSubscriber\ApiRateLimiterSubscriber:
    arguments:
      $apiLimiter: '@limiter.api'
      $loginLimiter: '@limiter.login'
      $forgotPasswordLimiter: '@limiter.forgot_password'
      $resetPasswordLimiter: '@limiter.reset_password'
      $refreshTokenLimiter: '@limiter.refresh_token'

  App\Service\Ticket\TicketStorageService:
    arguments:
      $projectDir: '%kernel.project_dir%'

  App\Service\Ticket\TicketPdfService:
    arguments:
      $projectDir: '%kernel.project_dir%'