symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600          # token valid for 1 hour
    throttle_limit: 900   # user can request a new token only once per hour (anti-spam)
